apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: pwngdb
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    dns: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    enabled: true
    image: eu.gcr.io/kctf-challenges/pwngdb-healthcheck:70374203c152bdf2fcb0b63fa83a851f6fbbc1c2d8ffa3c853675240858553f9
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: slash-tmp
                mountPath: /tmp
        volumes:
          - name: slash-tmp
            emptyDir: {}
  image: eu.gcr.io/kctf-challenges/pwngdb:3704567ffaeb2c5b77d81327491e1b61e8778773a298ccd4cee16a7ae50ff162
