apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: gdb-as-a-service
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    dns: true
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    enabled: true
    image: eu.gcr.io/kctf-challenges/gdb-as-a-service-healthcheck:70374203c152bdf2fcb0b63fa83a851f6fbbc1c2d8ffa3c853675240858553f9
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: slash-tmp
                mountPath: /tmp
        volumes:
          - name: slash-tmp
            emptyDir: {}
  image: eu.gcr.io/kctf-challenges/gdb-as-a-service:89873338fb5c80c994bf8a3182e8b73f3b102fb2bf13c56065e5d4db85751deb
