apiVersion: kctf.dev/v1alpha1
kind: Challenge
metadata:
  name: gdb-as-a-service
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    dns: false
    ports:
      - protocol: "HTTPS"
        targetPort: 1337
  healthcheck:
    enabled: true
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: slash-tmp
                mountPath: /tmp
        volumes:
          - name: slash-tmp
            emptyDir: {}
